#========================================
#===   killrvideo-service-ratings     ===
#========================================

application: 
    name: killrvideo-service-ratings

spring:
  output:
    ansi:
      enabled: ALWAYS

killrvideo:
  
  ##
  # Service discovery : 
  # - Locally will register and lookup etcd to allow dynamic scaling
  # - With Kubernetes use the service name and no lookup
  ##
  etcd:
    enabled: true
    host: 10.0.75.1
    port: 2379
    maxNumberOfTries: 30
    delayBetweenTries: 5

  ##
  # GRPC
  # - Default port for this microservice, will be inc by one if needed for each start (ETCD)
  # - In Kubernetes, will always uswe the default port expose by service,
  ##   
  grpc-server: 
    port: 30200
      
  ##
  # Connectivity to DSE
  # - Retry mecanism allow to sync containers startups
  # - With Kubernetes use the service name and no lookup
  ##  
  cassandra:
    maxNumberOfTries: 10
    delayBetweenTries: 2
    clustername: killrvideo
    mutation-error-log: /tmp/killrvideo-mutation-errors.log
    ssl:
      enable: false
      CACertFileLocation: cassandra.cert
      
  ##
  # Messaging
  # - Will be Kafka if microservices
  ##
  messaging:
    # Select proper transport kafka | inmemory
    transport: kafka 
    kafka:
      ack: 1
      consumerGroup: killrvideo
      topics:
        errors: topic-kv-errors
        videoRated: topic-kv-videoRating
        commentCreated: topic-kv-commentCreation
        userCreated: topic-kv-userCreation
        youTubeVideoAdded: topic-kv-videoCreation
    inmemory:
      minThreads: 5
      maxThreads: 10
      ttlThreads: 60
      queueSize: 1000  